<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEGxZUnD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEGxZUnD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEGxZUnD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEGxZUnD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEGxZUnD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EGxZUnD',
    'container.build_id' => '4077bf28',
    'container.build_time' => 1559121182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEGxZUnD');
