<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHGu07O5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHGu07O5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHGu07O5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHGu07O5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHGu07O5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HGu07O5',
    'container.build_id' => 'da3da4f2',
    'container.build_time' => 1558341163,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHGu07O5');
