<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZi85xay\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZi85xay/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZi85xay.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZi85xay\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZi85xay\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Zi85xay',
    'container.build_id' => '86efcb34',
    'container.build_time' => 1560946886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZi85xay');
